app = "alwaelydhs-proxy"
primary_region = "fra"

[processes]
  app = "python3 mtprotoproxy.py"

[[services]]
  internal_port = 443
  protocol = "tcp"
  # هذا السطر هو المفتاح
  processes = ["app"] 
  
  auto_start_machines = true
  auto_stop_machines = false

  [[services.ports]]
    port = 443
    handlers = []

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048