app = "alwaelydhs-proxy"
primary_region = "fra"

[[services]]
  internal_port = 443
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false # ضروري جداً لضمان عدم توقف السيرفر تلقائياً

  [[services.ports]]
    port = 443
    handlers = [] # إفراغ الـ handlers يجعل البيانات تمر "خام" للكود ليفك تشفيرها بنفسه

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048